(function(){
'use strict';
const round=n=>Math.round((Number(n)||0)*100)/100,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const yearOf=v=>String(v||'').slice(0,4),today=()=>new Date().toISOString().slice(0,10);
function years(state){const set=new Set([yearOf(state.currentPeriod)]);(state.customerInvoices||[]).forEach(x=>set.add(yearOf(x.issueDate||x.createdAt)));(state.corporateTaxReturns||[]).forEach(x=>set.add(String(x.year)));return [...set].filter(x=>/^\d{4}$/.test(x)).sort().reverse();}
function annualPnl(state,year){let revenue=0,net=0;for(let m=1;m<=12;m++){const s=window.DalasiProfitLoss?.statement?.(state,year+'-'+String(m).padStart(2,'0'))||{};revenue+=Number(s.revenue)||0;net+=Number(s.netProfit)||0;}return {turnover:round(revenue),accountingProfit:round(net)};}
function adjustments(state,year){return (state.corporateTaxAdjustments||[]).filter(x=>String(x.year)===String(year));}
function payments(state,year){return (state.corporateTaxPayments||[]).filter(x=>String(x.year)===String(year));}
function returnRecord(state,year){return (state.corporateTaxReturns||[]).find(x=>String(x.year)===String(year))||null;}
function filingRecord(state,year){return returnRecord(state,year)||{year:String(year),status:'Draft'};}
function evidenceReady(state,year){const c=computation(state,year),prov=(state.corporateTaxProvisions||[]).find(x=>String(x.year)===String(year)),rec=filingRecord(state,year);return {computation:c,provision:!!prov,reviewed:!!rec.reviewedAt,ready:!!rec.readyAt,canReview:!!prov,canReady:!!prov&&!!rec.reviewedAt,canFile:!!prov&&!!rec.reviewedAt&&!!rec.readyAt};}
function computation(state,year){
 const base=annualPnl(state,year),adj=adjustments(state,year);
 const addbacks=round(adj.filter(x=>x.kind==='Add-back').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const deductions=round(adj.filter(x=>x.kind==='Deduction').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const capitalAllowance=round(adj.filter(x=>x.kind==='Capital allowance').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const losses=round(adj.filter(x=>x.kind==='Loss brought forward').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const wht=round(adj.filter(x=>x.kind==='Withholding tax credit').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const foreign=round(adj.filter(x=>x.kind==='Foreign tax credit').reduce((a,x)=>a+(Number(x.amount)||0),0));
 const chargeable=round(Math.max(0,base.accountingProfit+addbacks-deductions-capitalAllowance-losses));
 const audited=state.corporateTaxAudited!==false,profitTax=round(chargeable*.27),turnoverTax=round(base.turnover*(audited?.01:.02)),grossTax=Math.max(profitTax,turnoverTax);
 const paid=round(payments(state,year).reduce((a,x)=>a+(Number(x.amount)||0),0)),credits=round(wht+foreign),netDue=round(Math.max(0,grossTax-paid-credits)),credit=round(Math.max(0,paid+credits-grossTax));
 return {...base,addbacks,deductions,capitalAllowance,losses,wht,foreign,chargeable,audited,profitTax,turnoverTax,grossTax,paid,credits,netDue,credit};
}
function render(state,h){
 const {pageTitle,icon,money2,pill}=h,year=String(state.corporateTaxYear||yearOf(state.currentPeriod)||years(state)[0]),c=computation(state,year),rec=filingRecord(state,year),filed=rec.status==='Filed',prov=(state.corporateTaxProvisions||[]).find(x=>String(x.year)===year),adj=adjustments(state,year),pays=payments(state,year),gate=evidenceReady(state,year),opts=years(state).map(y=>'<option '+(y===year?'selected':'')+'>'+y+'</option>').join('');
 const qs=['Q1','Q2','Q3','Q4'].map((q,i)=>{const due=[year+'-04-15',year+'-07-15',year+'-10-15',(Number(year)+1)+'-01-15'][i],amt=round(pays.filter(x=>x.quarter===q).reduce((a,x)=>a+(Number(x.amount)||0),0));return '<div class="surface"><span>'+q+' instalment</span><b>'+money2(amt)+'</b><small>Due '+due+'</small></div>'}).join('');
 return pageTitle('TAX COMPLIANCE','Corporate Income Tax','GRA corporation tax computation, instalments, annual filing and ledger posting.','<div class="inline-buttons"><button class="secondary" data-action="tax-view:vat">VAT</button><button class="secondary" data-action="tax-view:calendar">Compliance Calendar</button><select id="corporate-tax-year">'+opts+'</select><button class="secondary" data-action="cit-working-paper:'+year+'">'+icon('download',14)+' Working paper</button><button class="secondary" data-action="open-cit-adjustment">'+icon('plus',14)+' Tax adjustment</button><button class="secondary" data-action="open-cit-payment">'+icon('bank',14)+' Record instalment</button></div>')+
 '<div class="payment-notice"><span>'+icon('shield',17)+'</span><div><b>GRA corporation tax rule</b><p>'+(c.audited?'Audited':'Unaudited')+' accounts: higher of 27% of chargeable income or '+(c.audited?'1%':'2%')+' of turnover. Annual return due 31 March / three months after year-end.</p></div></div>'+
 '<div class="accounting-summary"><div class="surface"><span>Turnover</span><b>'+money2(c.turnover)+'</b></div><div class="surface"><span>Accounting profit</span><b>'+money2(c.accountingProfit)+'</b></div><div class="surface"><span>Chargeable income</span><b>'+money2(c.chargeable)+'</b></div><div class="surface"><span>Gross corporation tax</span><b>'+money2(c.grossTax)+'</b></div></div>'+ '<section class="surface employee-card"><div class="table-tools"><div><h3>Annual filing control</h3><p>Draft → Reviewed → Ready to File → Filed.</p></div>'+pill(rec.status||'Draft',rec.status==='Filed'?'ready':rec.status==='Ready to File'?'approved':'neutral')+'</div><div class="accounting-summary"><div class="surface"><span>Prepared by</span><b>'+esc(rec.preparedBy||state.session?.name||'Current user')+'</b><small>'+esc(rec.preparedAt||'Working paper')+'</small></div><div class="surface"><span>Reviewed by</span><b>'+esc(rec.reviewedBy||'Not reviewed')+'</b><small>'+esc(rec.reviewedAt||'')+'</small></div><div class="surface"><span>Ready to file</span><b>'+esc(rec.readyBy||'Not approved')+'</b><small>'+esc(rec.readyAt||'')+'</small></div><div class="surface"><span>Filed by</span><b>'+esc(rec.filedBy||'Not filed')+'</b><small>'+esc(rec.acknowledgementId||'')+'</small></div></div><div class="inline-buttons">'+(!gate.reviewed?'<button class="secondary" data-action="cit-review:'+year+'" '+(gate.canReview?'':'disabled')+'>Review return</button>':'')+(!gate.ready?'<button class="secondary" data-action="cit-ready:'+year+'" '+(gate.canReady?'':'disabled')+'>Mark ready to file</button>':'')+(!filed?'<button class="primary" data-action="open-cit-file:'+year+'" '+(gate.canFile?'':'disabled')+'>'+icon('check',14)+' File return</button>':'')+'</div></section>'+
 '<section class="surface employee-card"><div class="table-tools"><div><h3>Tax computation</h3><p>Accounting profit reconciled to chargeable income and compared with turnover minimum tax.</p></div><label>Accounts basis <select id="cit-audited"><option value="yes" '+(c.audited?'selected':'')+'>Audited</option><option value="no" '+(!c.audited?'selected':'')+'>Unaudited</option></select></label></div><table><tbody>'+
 [['Accounting profit',c.accountingProfit],['Add-backs',c.addbacks],['Less: allowable deductions',-c.deductions],['Less: capital allowance',-c.capitalAllowance],['Less: losses brought forward',-c.losses],['Chargeable income',c.chargeable],['27% of chargeable income',c.profitTax],[(c.audited?'1%':'2%')+' of turnover',c.turnoverTax],['Corporation tax liability',c.grossTax],['Less: instalments paid',-c.paid],['Less: withholding/foreign tax credits',-c.credits],['Final tax payable',c.netDue],['Tax credit position',c.credit]].map(r=>'<tr><td>'+esc(r[0])+'</td><td>'+money2(r[1])+'</td></tr>').join('')+'</tbody></table><div class="inline-buttons">'+(prov?pill('PROVISION POSTED','ready'):'<button class="primary" data-action="cit-post-provision:'+year+'">Post tax provision</button>')+' '+pill(rec.status||'Draft',filed?'ready':rec.status==='Ready to File'?'approved':'neutral')+'</div></section>'+
 '<div class="accounting-summary">'+qs+'</div>'+
 '<section class="surface employee-card"><div class="table-tools"><div><h3>Tax adjustments & credits</h3><p>Manual tax reconciliation items with audit trail.</p></div></div><div class="table-scroll"><table><thead><tr><th>TYPE</th><th>DESCRIPTION</th><th>AMOUNT</th></tr></thead><tbody>'+(adj.length?adj.map(x=>'<tr><td>'+esc(x.kind)+'</td><td>'+esc(x.description||'')+'</td><td>'+money2(x.amount)+'</td></tr>').join(''):'<tr><td colspan="3">No tax adjustments yet.</td></tr>')+'</tbody></table></div></section>'+
 '<section class="surface employee-card"><div class="table-tools"><div><h3>Quarterly and annual payment record</h3><p>Quarterly declarations are due 15 days after each quarter-end.</p></div></div><div class="table-scroll"><table><thead><tr><th>DATE</th><th>QUARTER</th><th>AMOUNT</th><th>REFERENCE</th></tr></thead><tbody>'+(pays.length?pays.map(x=>'<tr><td>'+esc(x.date)+'</td><td>'+esc(x.quarter||'Final')+'</td><td>'+money2(x.amount)+'</td><td>'+esc(x.reference||'')+'</td></tr>').join(''):'<tr><td colspan="4">No corporate tax payments recorded.</td></tr>')+'</tbody></table></div></section>';
}
function adjustmentModal(state,h){const {field}=h,year=state.corporateTaxYear||yearOf(state.currentPeriod);return '<div class="center-modal payment-modal"><div class="modal-scrim" data-action="close-cit-adjustment"></div><form id="cit-adjustment-form" class="modal-box"><div class="modal-head"><div><h2>Corporate tax adjustment</h2><p>'+esc(year)+'</p></div><button class="close" type="button" data-action="close-cit-adjustment">×</button></div><div class="form-grid">'+field('Type','<select name="kind"><option>Add-back</option><option>Deduction</option><option>Capital allowance</option><option>Loss brought forward</option><option>Withholding tax credit</option><option>Foreign tax credit</option></select>')+field('Amount','<input name="amount" type="number" min="0.01" step="0.01" required>')+field('Description','<input name="description" required placeholder="Tax adjustment basis / evidence">')+'</div><div class="modal-actions"><button class="primary">Save adjustment</button></div></form></div>'}
function saveAdjustment(ev,state,ctx){ev.preventDefault();const fd=new FormData(ev.target),amount=round(fd.get('amount'));if(amount<=0)return;state.corporateTaxAdjustments=state.corporateTaxAdjustments||[];state.corporateTaxAdjustments.unshift({id:'CITA-'+Date.now().toString(36).toUpperCase(),year:state.corporateTaxYear||yearOf(state.currentPeriod),kind:String(fd.get('kind')),amount,description:String(fd.get('description')||'').trim(),createdAt:new Date().toISOString(),createdBy:state.session?.name||'User'});state.citAdjustmentOpen=false;ctx.save();ctx.render();}
function paymentModal(state,h){const {field,money2}=h,year=state.corporateTaxYear||yearOf(state.currentPeriod),c=computation(state,year),acct=window.DalasiCashBank?.accountSelect?.(state,'accountId','','Account used to pay GRA')||'<select disabled></select>';return '<div class="center-modal payment-modal"><div class="modal-scrim" data-action="close-cit-payment"></div><form id="cit-payment-form" class="modal-box"><div class="modal-head"><div><h2>Record corporate tax payment</h2><p>'+esc(year)+' · estimated balance '+money2(c.netDue)+'</p></div><button class="close" type="button" data-action="close-cit-payment">×</button></div><div class="form-grid">'+field('Quarter','<select name="quarter"><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option value="">Final / other</option></select>')+field('Date','<input name="date" type="date" value="'+today()+'" required>')+field('Amount','<input name="amount" type="number" min="0.01" step="0.01" required>')+field('Cash & Bank account',acct)+field('Reference','<input name="reference" placeholder="GRA receipt / document ID">')+'</div><div class="modal-actions"><button class="primary">Record payment</button></div></form></div>'}
function savePayment(ev,state,ctx){ev.preventDefault();const fd=new FormData(ev.target),year=state.corporateTaxYear||yearOf(state.currentPeriod),date=String(fd.get('date')||''),amount=round(fd.get('amount')),accountId=String(fd.get('accountId')||'');if(!date||amount<=0||!accountId){ctx.toast('Enter a valid payment and bank account.');return}if(window.DalasiMonthClose?.isClosed(state,date)){ctx.toast('Payment date is in a closed period.');return}const tx=window.DalasiCashBank?.post?.(state,{accountId,date,direction:'out',amount,type:'Corporate income tax payment',counterparty:'Gambia Revenue Authority',reference:String(fd.get('reference')||''),description:'Corporate income tax '+year,sourceType:'corporate-tax-payment',sourceId:year,sourceKey:'cit:'+year+':'+Date.now(),createdBy:state.session?.name||'User'});if(!tx){ctx.toast('Choose a valid Cash & Bank account.');return}state.corporateTaxPayments=state.corporateTaxPayments||[];state.corporateTaxPayments.unshift({id:'CITPAY-'+Date.now().toString(36).toUpperCase(),year,quarter:String(fd.get('quarter')||''),date,amount,accountId,reference:String(fd.get('reference')||''),cashTransactionId:tx.id,createdAt:new Date().toISOString(),createdBy:state.session?.name||'User'});state.citPaymentOpen=false;ctx.save();ctx.render();}
function postProvision(year,state,ctx){if((state.corporateTaxProvisions||[]).some(x=>String(x.year)===String(year))){ctx.toast('Corporate tax provision already posted for '+year);return}const c=computation(state,year);if(c.grossTax<=0){ctx.toast('No corporation tax liability to provide.');return}const date=String(year)+'-12-31';if(window.DalasiMonthClose?.isClosed(state,date)){ctx.toast('December is closed. Reopen it before posting the tax provision.');return}state.corporateTaxProvisions=state.corporateTaxProvisions||[];state.corporateTaxProvisions.unshift({id:'CITPROV-'+Date.now().toString(36).toUpperCase(),year,date,amount:c.grossTax,reference:'CIT-'+year,createdAt:new Date().toISOString(),createdBy:state.session?.name||'User'});ctx.save();ctx.render();}
function ensureReturn(state,year){let rec=returnRecord(state,year);if(rec)return rec;state.corporateTaxReturns=state.corporateTaxReturns||[];rec={id:'CITR-'+Date.now().toString(36).toUpperCase(),year:String(year),status:'Draft',preparedAt:new Date().toISOString(),preparedBy:state.session?.name||'User',dueDate:(Number(year)+1)+'-03-31'};state.corporateTaxReturns.unshift(rec);return rec;}
function reviewReturn(year,state,ctx){const gate=evidenceReady(state,year);if(!gate.canReview){ctx.toast('Post the corporate tax provision before review.');return;}const rec=ensureReturn(state,year),actor=state.session?.name||'User';if(rec.preparedBy===actor){ctx.toast('A different authorized user should review the corporate tax return.');return;}rec.status='Reviewed';rec.reviewedAt=new Date().toISOString();rec.reviewedBy=actor;rec.snapshot=computation(state,year);ctx.audit('tax.corporate_reviewed',{year,returnId:rec.id});ctx.save();ctx.render();}
function markReady(year,state,ctx){const rec=ensureReturn(state,year);if(!rec.reviewedAt){ctx.toast('Review the return before marking it ready to file.');return;}rec.status='Ready to File';rec.readyAt=new Date().toISOString();rec.readyBy=state.session?.name||'User';rec.snapshot=computation(state,year);ctx.audit('tax.corporate_ready_to_file',{year,returnId:rec.id});ctx.save();ctx.render();}
function filingModal(state,h){const year=String(state.citFileYear||''),rec=year?ensureReturn(state,year):null;if(!year||!rec)return '';const {field,icon}=h;return '<div class="center-modal payment-modal"><div class="modal-scrim" data-action="close-cit-file"></div><form id="cit-file-form" class="modal-box"><div class="modal-head"><div><div class="eyebrow">GRA CORPORATE RETURN</div><h2>Record annual filing</h2><p>'+esc(year)+' · due '+esc(rec.dueDate||'')+'</p></div><button type="button" class="close" data-action="close-cit-file">×</button></div><div class="form-grid">'+field('GRA acknowledgement / document ID','<input name="acknowledgementId" required placeholder="Enter acknowledgement or document ID">')+field('Filing note','<textarea name="filingNote" rows="3" required placeholder="Portal submission / supporting evidence note"></textarea>')+'</div><div class="modal-actions"><button type="button" class="secondary" data-action="close-cit-file">Cancel</button><button class="primary" type="submit">'+icon('check',14)+' Confirm filed</button></div></form></div>';}
function fileReturn(ev,state,ctx){ev.preventDefault();const year=String(state.citFileYear||''),rec=returnRecord(state,year);if(!rec||rec.status!=='Ready to File'){ctx.toast('The return must be reviewed and marked ready before filing.');return;}const fd=new FormData(ev.target),ack=String(fd.get('acknowledgementId')||'').trim(),note=String(fd.get('filingNote')||'').trim();if(!ack||note.length<5){ctx.toast('Enter the GRA acknowledgement and filing evidence note.');return;}rec.status='Filed';rec.snapshot=computation(state,year);rec.acknowledgementId=ack;rec.filingNote=note;rec.filedAt=new Date().toISOString();rec.filedBy=state.session?.name||'User';state.citFileYear=null;ctx.audit('tax.corporate_filed',{year,returnId:rec.id,acknowledgementId:ack});ctx.save();ctx.render();}
function exportWorkingPaper(year,state,ctx){const c=computation(state,year),rec=filingRecord(state,year),adj=adjustments(state,year),pays=payments(state,year);const rows=[['DalasiPay GRA Corporate Income Tax Working Paper',year],['Return status',rec.status||'Draft'],['Due date',(Number(year)+1)+'-03-31'],['Accounts basis',c.audited?'Audited':'Unaudited'],[],['Tax computation','Amount'],['Turnover',c.turnover],['Accounting profit',c.accountingProfit],['Add-backs',c.addbacks],['Allowable deductions',c.deductions],['Capital allowance',c.capitalAllowance],['Losses brought forward',c.losses],['Chargeable income',c.chargeable],['27% chargeable-income tax',c.profitTax],[(c.audited?'1%':'2%')+' turnover minimum tax',c.turnoverTax],['Corporation tax liability',c.grossTax],['Withholding tax credits',c.wht],['Foreign tax credits',c.foreign],['Instalments paid',c.paid],['Final tax payable',c.netDue],['Tax credit position',c.credit],[],['Tax adjustments','Type','Description','Amount'],...adj.map(x=>['',x.kind,x.description,x.amount]),[],['Payments','Quarter','Date','Amount','Reference'],...pays.map(x=>['',x.quarter||'Final',x.date,x.amount,x.reference||'']),[],['Review / filing evidence'],['Prepared by',rec.preparedBy||''],['Prepared at',rec.preparedAt||''],['Reviewed by',rec.reviewedBy||''],['Reviewed at',rec.reviewedAt||''],['Ready by',rec.readyBy||''],['Ready at',rec.readyAt||''],['Filed by',rec.filedBy||''],['Filed at',rec.filedAt||''],['GRA acknowledgement',rec.acknowledgementId||''],['Filing note',rec.filingNote||'']];const csv=rows.map(r=>r.map(v=>{const q=String(v??'');return /[",\n]/.test(q)?'"'+q.replace(/"/g,'""')+'"':q}).join(',')).join('\n');ctx.downloadText('dalasipay-gra-corporate-tax-working-paper-'+year+'.csv',csv);ctx.toast('Corporate tax working paper downloaded');}
window.DalasiCorporateTax={years,computation,render,adjustmentModal,saveAdjustment,paymentModal,savePayment,postProvision,ensureReturn,reviewReturn,markReady,filingModal,fileReturn,exportWorkingPaper,returnRecord,filingRecord,evidenceReady};
})();