(function(){
'use strict';
const round=n=>Math.round((Number(n)||0)*100)/100;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10),periodOf=v=>String(v||'').slice(0,7);
const invoice=(s,id)=>(s.customerInvoices||[]).find(x=>x.id===id)||null,bill=(s,id)=>(s.businessBills||[]).find(x=>x.id===id)||null;
function nextNo(prefix,rows,key){const y=new Date().getFullYear(),base=prefix+'-'+y+'-',ns=(rows||[]).map(x=>String(x[key]||'')).filter(x=>x.startsWith(base)).map(x=>Number(x.slice(base.length))||0);return base+String((ns.length?Math.max(...ns):0)+1).padStart(5,'0')}
function customerFor(s,id){return (s.customerDebitNotes||[]).filter(x=>x.invoiceId===id&&x.status!=='Void')}
function supplierFor(s,id){return (s.supplierDebitNotes||[]).filter(x=>x.billId===id&&x.status!=='Void')}
function customerDebited(s,id){return round(customerFor(s,id).reduce((a,x)=>a+(Number(x.amount)||0),0))}
function supplierDebited(s,id){return round(supplierFor(s,id).reduce((a,x)=>a+(Number(x.amount)||0),0))}
function taxShare(s,doc,amount,side){return window.DalasiReturns?.taxShare?.(s,doc,amount,side)||window.DalasiTax?.snapshot?.(s,amount,doc?.taxCode||'OUT',side)||{taxCode:'OUT',vatRate:0,taxGross:amount,taxNet:amount,vatAmount:0,vatRecoverable:false,taxableTurnover:false}}
function validDate(date,s,ctx){if(!date){ctx.toast('Debit note date is required.');return false}if(window.DalasiMonthClose?.isClosed?.(s,date)){ctx.toast('That accounting period is closed. Reopen it before posting a debit note.');return false}if(window.DalasiTax?.returnRecord?.(s,periodOf(date))){ctx.toast('The VAT return for '+periodOf(date)+' is filed. Reopen it before posting a debit note in that period.');return false}return true}
function customerModal(s,h){const {field,icon,money2}=h,rows=(s.customerInvoices||[]).filter(x=>(window.DalasiSalesInvoices?.status?.(s,x)||x.status)!=='Draft'),sel=invoice(s,s.customerDebitInvoiceId)||rows[0]||null,opts=rows.map(x=>'<option value="'+esc(x.id)+'" '+(sel?.id===x.id?'selected':'')+'>'+esc(x.invoiceNo||x.id)+' · '+esc(x.customerName||'Customer')+' · current '+money2(window.DalasiReturns?.invoiceBalance?.(s,x)??x.amount)+'</option>').join('');
return '<div class="center-modal payment-modal"><div class="modal-scrim" data-action="close-customer-debit"></div><form id="customer-debit-form" class="modal-box">'+
'<div class="modal-head"><div><div class="eyebrow">CUSTOMER DEBIT NOTE</div><h2>Add customer charge</h2><p>Increase an issued invoice without rewriting the original.</p></div><button type="button" class="close" data-action="close-customer-debit">×</button></div>'+
(rows.length?'<div class="form-grid">'+field('Invoice','<select id="customer-debit-invoice-select" name="invoiceId">'+opts+'</select>')+field('Debit date','<input name="date" type="date" value="'+today()+'" required>')+field('Additional charge (GMD)','<input name="amount" type="number" min="0.01" step="0.01" required>')+field('Reason','<select name="reason"><option>Price correction</option><option>Additional service</option><option>Underbilling correction</option><option>Late / contractual charge</option><option>Other</option></select>')+'</div>'+field('Reference / note','<input name="note" placeholder="Reason for additional charge">')+'<div class="modal-note">VAT follows the linked invoice treatment. The debit increases Accounts Receivable and uses the original invoice due date for ageing.</div><div class="modal-actions"><button type="button" class="secondary" data-action="close-customer-debit">Cancel</button><button class="primary" type="submit">'+icon('check',14)+' Issue debit note</button></div>':'<div class="empty-inline">No issued customer invoice is available.</div>')+'</form></div>'}
function supplierModal(s,h){const {field,icon,money2}=h,rows=(s.businessBills||[]).filter(x=>(x.status||'Draft')!=='Draft'),sel=bill(s,s.supplierDebitBillId)||rows[0]||null,opts=rows.map(x=>'<option value="'+esc(x.id)+'" '+(sel?.id===x.id?'selected':'')+'>'+esc(x.invoiceNo||x.id)+' · '+esc(x.supplier||'Supplier')+' · current '+money2(window.DalasiReturns?.billBalance?.(s,x)??x.amount)+'</option>').join('');
return '<div class="center-modal payment-modal"><div class="modal-scrim" data-action="close-supplier-debit"></div><form id="supplier-debit-form" class="modal-box">'+
'<div class="modal-head"><div><div class="eyebrow">SUPPLIER ADDITIONAL CHARGE</div><h2>Record supplier debit</h2><p>Increase a supplier bill without editing the original document.</p></div><button type="button" class="close" data-action="close-supplier-debit">×</button></div>'+
(rows.length?'<div class="form-grid">'+field('Supplier bill','<select id="supplier-debit-bill-select" name="billId">'+opts+'</select>')+field('Debit date','<input name="date" type="date" value="'+today()+'" required>')+field('Additional charge (GMD)','<input name="amount" type="number" min="0.01" step="0.01" required>')+field('Supplier reference','<input name="supplierReference" placeholder="Supplier debit / adjustment ref">')+'</div>'+field('Reason / note','<input name="note" placeholder="Price correction, freight, service or other charge">')+'<div class="modal-note">VAT follows the linked supplier bill treatment. The debit increases Accounts Payable and keeps the original bill due date for ageing.</div><div class="modal-actions"><button type="button" class="secondary" data-action="close-supplier-debit">Cancel</button><button class="primary" type="submit">'+icon('check',14)+' Record supplier debit</button></div>':'<div class="empty-inline">No approved or paid supplier bill is available.</div>')+'</form></div>'}
function saveCustomer(ev,s,ctx){ev.preventDefault();if(!(ctx.can('workspace.manage')||ctx.can('payroll.manage'))){ctx.toast('Owner or Payroll Admin access is required to issue debit notes.');return}const fd=new FormData(ev.target),inv=invoice(s,String(fd.get('invoiceId')||'')),date=String(fd.get('date')||''),amount=round(fd.get('amount'));if(!inv||amount<=0){ctx.toast('Choose an invoice and enter a valid amount.');return}if(!validDate(date,s,ctx))return;const tax=taxShare(s,inv,amount,'sale'),id='CDN-'+Date.now().toString(36).toUpperCase(),debitNo=nextNo('DN',s.customerDebitNotes||[],'debitNo'),rec={id,debitNo,invoiceId:inv.id,invoiceNo:inv.invoiceNo||inv.id,customerId:inv.customerId||null,customerName:inv.customerName||'Customer',date,dueDate:inv.dueDate||date,amount,...tax,reason:String(fd.get('reason')||'Other'),note:String(fd.get('note')||'').trim(),status:'Issued',createdAt:new Date().toISOString(),createdBy:s.session?.name||'User'};s.customerDebitNotes=s.customerDebitNotes||[];s.customerDebitNotes.unshift(rec);s.customerDebitInvoiceId=null;ctx.audit('debits.customer_issued',{debitNoteId:id,debitNo,invoiceId:inv.id,amount});ctx.save();ctx.toast(debitNo+' issued');ctx.render()}
function saveSupplier(ev,s,ctx){ev.preventDefault();if(!(ctx.can('workspace.manage')||ctx.can('payroll.manage'))){ctx.toast('Owner or Payroll Admin access is required to record supplier debit notes.');return}const fd=new FormData(ev.target),b=bill(s,String(fd.get('billId')||'')),date=String(fd.get('date')||''),amount=round(fd.get('amount'));if(!b||amount<=0){ctx.toast('Choose a supplier bill and enter a valid amount.');return}if(!validDate(date,s,ctx))return;const tax=taxShare(s,b,amount,'purchase'),id='SDN-'+Date.now().toString(36).toUpperCase(),debitNo=nextNo('SDN',s.supplierDebitNotes||[],'debitNo'),rec={id,debitNo,billId:b.id,billNo:b.invoiceNo||b.id,beneficiaryId:b.beneficiaryId||null,supplier:b.supplier||'Supplier',date,dueDate:b.dueDate||date,amount,...tax,supplierReference:String(fd.get('supplierReference')||'').trim(),note:String(fd.get('note')||'').trim(),status:'Issued',createdAt:new Date().toISOString(),createdBy:s.session?.name||'User'};s.supplierDebitNotes=s.supplierDebitNotes||[];s.supplierDebitNotes.unshift(rec);s.supplierDebitBillId=null;ctx.audit('debits.supplier_recorded',{debitNoteId:id,debitNo,billId:b.id,amount});ctx.save();ctx.toast(debitNo+' recorded');ctx.render()}
function summary(s){const c=round((s.customerDebitNotes||[]).filter(x=>x.status!=='Void').reduce((a,x)=>a+(Number(x.amount)||0),0)),p=round((s.supplierDebitNotes||[]).filter(x=>x.status!=='Void').reduce((a,x)=>a+(Number(x.amount)||0),0));return {customerDebits:c,supplierDebits:p,customerNotes:(s.customerDebitNotes||[]).length,supplierNotes:(s.supplierDebitNotes||[]).length}}
function exportCsv(s,type,ctx){const customer=type!=='supplier',rows=customer?(s.customerDebitNotes||[]):(s.supplierDebitNotes||[]),head=customer?['Debit Note','Date','Customer','Invoice','Due Date','Gross Debit','Net Debit','VAT Added','Reason','Status']:['Debit Note','Date','Supplier','Bill','Due Date','Supplier Ref','Gross Debit','Net Debit','VAT Added','Status'],data=rows.map(x=>customer?[x.debitNo,x.date,x.customerName,x.invoiceNo,x.dueDate,x.amount,x.taxNet,x.vatAmount,x.reason,x.status]:[x.debitNo,x.date,x.supplier,x.billNo,x.dueDate,x.supplierReference||'',x.amount,x.taxNet,x.vatAmount,x.status]),csv=[head,...data].map(r=>r.map(v=>{const q=String(v??'');return /[",\n]/.test(q)?'"'+q.replace(/"/g,'""')+'"':q}).join(',')).join('\n');ctx.downloadText('dalasipay-'+(customer?'customer':'supplier')+'-debit-notes-'+today()+'.csv',csv);ctx.toast('Debit-note register downloaded')}
function pdf(id,type,s,ctx){const customer=type!=='supplier',x=(customer?s.customerDebitNotes:s.supplierDebitNotes||[]).find(r=>r.id===id);if(!x){ctx.toast('Debit note not found');return}const party=customer?x.customerName:x.supplier,source=customer?x.invoiceNo:x.billNo,title=customer?'DEBIT NOTE':'SUPPLIER DEBIT NOTE',out=[],ink='0.06 0.13 0.11',muted='0.36 0.43 0.40',green='0.04 0.31 0.26',line='0.84 0.88 0.86',white='1 1 1',soft='0.97 0.98 0.975',mint='0.92 0.97 0.95';const safe=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\u2018\u2019\u201C\u201D]/g,"'").replace(/[\u2013\u2014\u2212]/g,'-').replace(/[^\x20-\x7E]/g,'?').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)'),clip=(v,m=46)=>String(v??'').length>m?String(v).slice(0,m-3)+'...':String(v??''),text=(a,b,z,v,bold=false,c=ink)=>out.push(c+' rg BT /'+(bold?'F2':'F1')+' '+z+' Tf '+a+' '+b+' Td ('+safe(v)+') Tj ET'),fill=(a,b,w,h,c)=>out.push(c+' rg '+a+' '+b+' '+w+' '+h+' re f'),stroke=(a,b,c,d,col=line,w=.7)=>out.push(col+' RG '+w+' w '+a+' '+b+' m '+c+' '+d+' l S'),rect=(a,b,w,h,f=white,sc=line)=>{fill(a,b,w,h,f);out.push(sc+' RG .65 w '+a+' '+b+' '+w+' '+h+' re S')},label=(a,b,v)=>text(a,b,7.2,String(v).toUpperCase(),true,'0.42 0.49 0.46'),money=v=>ctx.money2(Number(v)||0),ts=window.DalasiTax?.settings?.(s)||{};
fill(0,0,595,842,white);out.push('0.88 0.91 0.90 RG .75 w 24 24 547 794 re S');fill(24,746,547,72,green);fill(24,746,5,72,'0.37 0.82 0.68');if(s.branding?.logoData)out.push('q 42 0 0 42 43 765 cm /Im1 Do Q');else{fill(43,765,42,42,'0.88 0.97 0.94');text(57,780,14,clip(s.branding?.logoText||s.company.slice(0,1),3),true,green)}text(99,790,17,clip(s.company,29),true,white);text(99,771,8.2,ts.tin?'TIN '+clip(ts.tin,26):'DALASIPAY DEBIT NOTES',true,'0.74 0.91 0.86');text(customer?420:357,791,customer?17:14,title,true,white);text(387,772,7.4,'ADDITIONAL CHARGE',true,'0.74 0.91 0.86');
rect(24,695,547,38,soft);label(40,718,'Debit note no.');text(40,703,10,x.debitNo||x.id,true);stroke(218,701,218,726);label(235,718,'Debit date');text(235,703,9.4,x.date,true);stroke(391,701,391,726);label(408,718,customer?'Invoice':'Supplier bill');text(408,703,9.4,clip(source,22),true);
rect(24,607,547,73,'0.945 0.97 0.96');label(40,662,customer?'Customer':'Supplier');text(40,644,13,clip(party,42),true);text(40,628,8.4,'Due '+(x.dueDate||'Not recorded'),false,muted);label(385,662,'Additional charge');text(385,638,19,money(x.amount),true,green);
rect(24,438,547,154,white);label(40,571,'Debit note details');const rows=customer?[['Reason',x.reason||'Additional charge'],['Reference / note',x.note||'Not recorded'],['Net value added',money(x.taxNet??x.amount)],['VAT added'+(x.vatRate?' · '+x.vatRate+'%':''),money(x.vatAmount||0)],['Original invoice',source]]:[['Supplier reference',x.supplierReference||'Not recorded'],['Reference / note',x.note||'Not recorded'],['Net value added',money(x.taxNet??x.amount)],['VAT added'+(x.vatRate?' · '+x.vatRate+'%':''),money(x.vatAmount||0)],['Original supplier bill',source]];rows.forEach((r,i)=>{const y=546-i*25;text(40,y,8.6,r[0],false,muted);text(205,y,9.2,clip(r[1],48),true);if(i<4)stroke(40,y-9,555,y-9,'0.91 0.93 0.92',.45)});
rect(24,315,547,101,mint);label(40,395,'Accounting effect');text(40,371,8.6,customer?'Accounts receivable increases':'Accounts payable increases',false,muted);text(245,368,15,money(x.amount),true,green);text(40,342,8.6,'VAT treatment',false,muted);text(205,342,9.2,clip(window.DalasiTax?.code?.(x.taxCode)?.label||x.taxCode||'Out of scope',30),true);
fill(24,210,547,75,green);text(42,257,8.2,customer?'TOTAL CUSTOMER DEBIT':'TOTAL SUPPLIER DEBIT',true,'0.74 0.91 0.86');text(42,229,22,money(x.amount),true,white);text(375,239,8,clip(x.status||'Issued',20),true,'0.84 0.95 0.91');stroke(24,82,571,82);text(24,63,7.3,customer?'This debit note increases the linked customer invoice and related VAT where applicable.':'This debit note records an additional supplier charge against the linked bill and related VAT where applicable.',true,'0.45 0.51 0.49');text(24,48,6.9,'The original invoice or bill remains unchanged; this adjustment is recorded separately for audit purposes.',false,'0.53 0.58 0.56');text(421,63,7.3,'Generated by DalasiPay',true,green);const fn=(customer?'Customer_Debit_Note_':'Supplier_Debit_Note_')+(String(party).replace(/[^A-Za-z0-9_-]+/g,'_')||'Party')+'_'+(x.debitNo||x.id)+'.pdf';ctx.pdfDownload(fn,out.join('\n'),s.branding?.logoData||'');ctx.toast((customer?'Customer':'Supplier')+' debit note PDF downloaded')}
function render(s,h){const {pageTitle,icon,money2,pill}=h,view=s.debitView==='supplier'?'supplier':'customer',m=summary(s),cr=(s.customerDebitNotes||[]).map(x=>'<tr><td><b>'+esc(x.debitNo)+'</b><small>'+esc(x.invoiceNo)+'</small></td><td>'+esc(x.date)+'</td><td>'+esc(x.customerName)+'</td><td>'+money2(x.amount)+'</td><td>'+money2(x.vatAmount||0)+'</td><td>'+esc(x.dueDate||'—')+'</td><td>'+pill(x.status||'Issued','approved')+'</td><td><button class="secondary tiny" data-action="debit-pdf:customer:'+esc(x.id)+'">'+icon('download',12)+' PDF</button></td></tr>').join('')||'<tr><td colspan="8"><div class="empty-inline">No customer debit notes issued yet.</div></td></tr>',sr=(s.supplierDebitNotes||[]).map(x=>'<tr><td><b>'+esc(x.debitNo)+'</b><small>'+esc(x.billNo)+'</small></td><td>'+esc(x.date)+'</td><td>'+esc(x.supplier)+'</td><td>'+money2(x.amount)+'</td><td>'+money2(x.vatAmount||0)+'</td><td>'+esc(x.dueDate||'—')+'</td><td>'+pill(x.status||'Issued','approved')+'</td><td><button class="secondary tiny" data-action="debit-pdf:supplier:'+esc(x.id)+'">'+icon('download',12)+' PDF</button></td></tr>').join('')||'<tr><td colspan="8"><div class="empty-inline">No supplier debit notes recorded yet.</div></td></tr>';
return pageTitle('ADDITIONAL CHARGES','Debit Notes','Increase customer or supplier balances through separate auditable adjustments without editing original documents.','<div class="inline-buttons"><button class="secondary" data-action="debit-export">'+icon('download',14)+' Export</button><button class="primary" data-action="'+(view==='customer'?'open-customer-debit':'open-supplier-debit')+'">'+icon('plus',14)+' '+(view==='customer'?'Customer debit':'Supplier debit')+'</button></div>')+
'<div class="debit-tabs"><button class="'+(view==='customer'?'active':'')+'" data-action="debit-view:customer">Customer debits</button><button class="'+(view==='supplier'?'active':'')+'" data-action="debit-view:supplier">Supplier debits</button></div>'+
'<div class="debit-kpis"><div class="surface"><span>Customer debit notes</span><b>'+money2(m.customerDebits)+'</b><small>'+m.customerNotes+' documents</small></div><div class="surface"><span>Supplier debit notes</span><b>'+money2(m.supplierDebits)+'</b><small>'+m.supplierNotes+' documents</small></div><div class="surface"><span>Balance impact</span><b>'+money2(view==='customer'?m.customerDebits:m.supplierDebits)+'</b><small>added to linked '+(view==='customer'?'receivables':'payables')+'</small></div></div>'+
'<div class="payment-notice"><span>'+icon('file',17)+'</span><div><b>Additional charges stay separate from the original document</b><p>Debit notes increase the linked balance and VAT where applicable. They do not change inventory quantities.</p></div></div>'+
'<section class="surface employee-card debit-register"><div class="table-tools"><div><h3>'+(view==='customer'?'Customer debit-note register':'Supplier debit-note register')+'</h3><p>Additional charges and VAT added to existing documents</p></div></div><div class="table-scroll"><table><thead><tr><th>DEBIT / SOURCE</th><th>DATE</th><th>'+(view==='customer'?'CUSTOMER':'SUPPLIER')+'</th><th>GROSS DEBIT</th><th>VAT</th><th>DUE DATE</th><th>STATUS</th><th>DOCUMENT</th></tr></thead><tbody>'+(view==='customer'?cr:sr)+'</tbody></table></div></section>'}
window.DalasiDebits={customerFor,supplierFor,customerDebited,supplierDebited,customerModal,supplierModal,saveCustomer,saveSupplier,summary,exportCsv,pdf,render};
})();