const annualPrice=p=>Number.isSafeInteger(p.annual_price_gmd)&&p.annual_price_gmd>=0&&p.currency_code==='GMD'&&p.billing_period_months===12?'D'+p.annual_price_gmd.toLocaleString('en-GB')+' per year (GMD · 12 months)':'Annual price unavailable';
const escape=v=>String(v??'Not recorded').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const limits=['companies','users','employees','invoicesPerMonth','supplierBillsPerMonth'];
const features=['coreAccounting','smallBusinessPayroll','recurringBilling','projects','budgets','advancedReports','fullPayroll','makerChecker','periodClose','advancedTaxCompliance','auditControls'];
const labels=v=>String(v).replace(/([A-Z])/g,' $1').replace(/[_-]/g,' ').replace(/^./,c=>c.toUpperCase());
const input=(name,value,type='text',extra='')=>`<label>${escape(labels(name))}<input name="${name}" type="${type}" value="${escape(value??'')}" ${extra}></label>`;
const field=(label,value)=>`<div class="fact"><small>${escape(label)}</small><strong>${escape(value)}</strong></div>`;
const link=id=>'/business?id='+encodeURIComponent(id);
const table=(heads,rows)=>`<section class="scroll"><table><thead><tr>${heads.map(x=>`<th>${escape(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></section>`;
const history=rows=>rows.length?table(['Action','Date (UTC)','Previous plan','Proposed plan'],rows.map(x=>`<tr><td>${escape(labels(x.event_type))}</td><td>${escape(x.happened_at)}</td><td>${escape(x.previous_plan)}</td><td>${escape(x.proposed_plan)}</td></tr>`)):'<p>No subscription history recorded.</p>';
export const managementNav=`<nav aria-label="Administration"><a href="/">Subscriptions</a><a href="/businesses">Businesses</a><a href="/plans">Plan drafts</a><a href="/requests">Requests</a><a href="/billing">Billing</a><a href="/audit">Audit history</a><a href="/settings">Settings</a></nav>`;
export function renderManagement(view,data,{offset=0,notice=''}={}){
 const titles={businesses:'Business directory',business:'Business profile',plans:'Licensing plan drafts',requests:'Subscription requests',audit:'Administrative audit history',billing:'Annual subscription billing',wave_settings:'Wave payment settings'};
 let content='';const rows=Array.isArray(data.rows)?data.rows.slice(0,100):[];if(view==='plans')rows.sort((a,b)=>['free','standard','professional'].indexOf(a.plan_id)-['free','standard','professional'].indexOf(b.plan_id));
 if(view==='businesses')content=table(['Business','Registered (UTC)','Subscription','Entitlement','Renewal planning date','Members'],rows.map(x=>`<tr><td><a href="${link(x.id)}">${escape(x.name)}</a><small>${escape(x.id)}</small></td><td>${escape(x.created_at)}</td><td>${escape(labels(x.plan_id??'Not recorded'))}<small>${escape(labels(x.status??'Not recorded'))}</small></td><td>${x.professional_preview?'Unlimited Professional Preview':'Not recorded as preview'}</td><td>${escape(x.renewal_date)}</td><td>${escape(x.member_count)}</td></tr>`));
 if(view==='business'){
  const p=data.profile,s=data.subscription??{},d=data.details??{};
  content=`<h2>${escape(p.name)}</h2><div class="facts">${field('Workspace ID',p.id)}${field('Account email',data.account?.email)}${field('Account confirmed',data.account?.confirmed?'Yes':'No')}${field('Members',data.members)}${field('Industry',p.industry)}${field('Business size',p.size_band)}${field('Currency',p.currency)}${field('Created (UTC)',p.created_at)}${field('Plan',s.plan_id)}${field('Status',s.status)}${field('Entitlement',s.professional_preview?'Unlimited Professional Preview':'Not recorded as preview')}${field('Renewal planning date',d.renewal_date)}</div>
  <h2>Renewal planning and account notes</h2><p>These notes and dates are administrative records. Saving them does not renew, bill, restrict, or alter the subscription.</p><form method="post" action="/manage"><input type="hidden" name="action" value="save_details"><input type="hidden" name="id" value="${escape(p.id)}"><input type="hidden" name="version" value="${d.version??0}">${input('renewal_date',d.renewal_date,'date')}<label>Account notes<textarea name="notes" maxlength="2000">${escape(d.notes??'')}</textarea></label><button>Save planning details</button></form>
  <h2>Subscription history</h2>${history(data.history??[])}<h2>Requests</h2>${table(['Type','Requested plan','Status','Reason'],(data.requests??[]).map(r=>`<tr><td>${escape(labels(r.request_kind))}</td><td>${escape(r.requested_plan)}</td><td>${escape(r.status)}</td><td>${escape(r.reason)}</td></tr>`))}`;
 }
 if(view==='plans')content='<p>Configuration is draft-only. Existing previews stay unlimited. Limits, features, and billing are not applied to customer accounts.</p><div class="plans">'+rows.map(p=>`<article><h2>${escape(p.label)}</h2><p><strong>${escape(annualPrice(p))}</strong></p><p>Draft version ${p.version}</p><details><summary>Edit annual pricing draft</summary><p>Explicit owner authorization is required. Saving changes the catalogue draft only.</p><form method="post" action="/manage"><input type="hidden" name="action" value="save_price"><input type="hidden" name="plan_id" value="${escape(p.plan_id)}"><input type="hidden" name="version" value="${p.version}">${input('annual_price_gmd',p.annual_price_gmd,'number','required min="0" max="9999999" step="1"')}<label>Authorization reason<textarea name="reason" required minlength="10" maxlength="1000"></textarea></label><label class="check"><input name="confirmed" type="checkbox" value="yes" required>I authorize this annual pricing draft change.</label><button>Save authorized price draft</button></form></details><form method="post" action="/manage"><input type="hidden" name="action" value="save_plan"><input type="hidden" name="plan_id" value="${p.plan_id}"><input type="hidden" name="version" value="${p.version}">${input('label',p.label,'text','required maxlength="80"')}<h3>Draft limits</h3><p>Leave a limit blank for unlimited.</p>${limits.map(k=>input(k,p.limits[k],'number','min="0" max="9999999" step="1"')).join('')}<h3>Draft features</h3>${features.map(k=>`<label class="check"><input type="checkbox" name="features" value="${k}" ${p.features.includes(k)?'checked':''}>${escape(labels(k))}</label>`).join('')}<button>Save draft</button></form></article>`).join('')+'</div>';
 if(view==='plans')content+='<h2>Feature comparison</h2>'+table(['Feature',...rows.map(p=>p.label)],features.map(k=>'<tr><td>'+escape(labels(k))+'</td>'+rows.map(p=>'<td>'+(p.features.includes(k)?'Included':'Not included')+'</td>').join('')+'</tr>'));
 if(view==='billing')content='<p>Annual billing foundation only. Invoice issuance, payment collection and reminder delivery are disabled. No subscription access changes are performed.</p>'+(rows.length?table(['Invoice','Business','Annual amount','Payment status','Service start','Renewal'],rows.map(i=>'<tr><td>'+escape(i.invoice_number)+'</td><td>'+escape(i.business_name)+'</td><td>GMD '+escape((i.amount_minor/100).toLocaleString('en-GB'))+'</td><td>'+escape(i.payment_status)+'</td><td>'+escape(i.service_start)+'</td><td>'+escape(i.service_end)+'</td></tr>')):'<p>No subscription invoices or payments recorded.</p>');
 if(view==='wave_settings')content='<p>Wave is the only subscription payment method. There is no Wave API connection. Recipient details are withheld from customers while billing is disabled. Saving settings does not authorize commercial launch.</p>'+(data.owner_can_configure?'<form method="post" action="/manage"><input type="hidden" name="action" value="save_wave_settings"><input type="hidden" name="version" value="'+escape(data.version)+'">'+input('phone',data.phone,'tel','required maxlength="16" placeholder="International phone number"')+input('account_name',data.account_name,'text','required minlength="2" maxlength="100"')+'<label>Authorization reason<textarea name="reason" required minlength="10" maxlength="1000"></textarea></label><label class="check"><input type="checkbox" name="confirmed" value="yes" required>I have verified this receiving Wave account and authorize saving these details.</label><button>Save Wave settings</button></form>':'<p>Only the verified platform owner can configure the receiving account.</p>');
 if(view==='billing')content+='<h2>Manual Wave verification</h2><p>Statuses: Pending Verification · Verified · Rejected. Screenshots and references are supporting evidence only. Independently check actual Wave transaction history before confirming. Verification never activates entitlements.</p>'+((data.payments||[]).length?(data.payments||[]).map(p=>'<article><h3>'+escape(p.business_name)+'</h3><p>'+escape(p.invoice_number)+' · GMD '+escape((p.amount_minor/100).toLocaleString('en-GB'))+' · '+escape(p.status)+'</p><p>Wave reference: '+escape(p.reference)+'</p><p>Review reason: '+escape(p.review_note??'Awaiting review')+'</p>'+(p.evidence_attached?'<a href="/wave-evidence?id='+encodeURIComponent(p.id)+'">Download private evidence</a>':'<p>No screenshot attached.</p>')+(p.receipt_number?'<p><a href="/wave-receipt?id='+encodeURIComponent(p.id)+'">Print Wave receipt '+escape(p.receipt_number)+'</a></p>':'')+(p.status==='Pending Verification'&&p.submitted_by!==data.actor_id?'<form method="post" action="/manage"><fieldset '+(data.review_enabled?'':'disabled')+'><input type="hidden" name="action" value="review_wave_payment"><input type="hidden" name="id" value="'+escape(p.id)+'"><input type="hidden" name="version" value="'+escape(p.version)+'"><label>Decision<select name="decision"><option value="verified">Verified against Wave history</option><option value="rejected">Rejected</option></select></label><label class="check"><input type="checkbox" name="history_checked" value="yes">I independently checked this incoming transaction in actual Wave transaction history.</label>'+input('checked_reference','','text','maxlength="100"')+input('checked_amount_gmd','','number','min="0" step="1"')+'<label>Review reason<textarea name="note" required minlength="10" maxlength="1000"></textarea></label><button>Record independent review</button></fieldset></form>':'')+'</article>').join(''):'<p>No Wave payment submissions. Customer submissions and verification are disabled during development.</p>');
 if(view==='billing')content+='<h2>Payment audit history</h2>'+((data.events||[]).length?table(['Action','Date (UTC)','Actor','Invoice','Details'],data.events.map(e=>'<tr><td>'+escape(e.event_type)+'</td><td>'+escape(e.happened_at)+'</td><td>'+escape(e.actor_user_id)+'</td><td>'+escape(e.invoice_id)+'</td><td><pre>'+escape(JSON.stringify(e.metadata))+'</pre></td></tr>')):'<p>No payment audit events recorded.</p>');
 if(view==='requests')content='<p>Approval records a review decision only. It does not change a plan, take payment, renew access, or enforce limits. Administrators cannot review their own requests.</p>'+ (rows.length?rows.map(r=>`<article><h2><a href="${link(r.organization_id)}">${escape(r.business_name)}</a></h2><p>${escape(labels(r.request_kind))} · ${escape(r.requested_plan)} · <strong>${escape(r.status)}</strong></p><p>${escape(r.reason)}</p><small>Requested ${escape(r.created_at)} · ${escape(r.requested_by)}</small>${r.status==='pending'&&r.requested_by!==data.actor_id?`<form method="post" action="/manage"><input type="hidden" name="action" value="review"><input type="hidden" name="id" value="${escape(r.id)}"><label>Review decision<select name="decision"><option value="approved">Approve request only</option><option value="rejected">Reject</option></select></label><label>Review note<textarea name="note" required minlength="10" maxlength="1000"></textarea></label><button>Record decision</button></form>`:`<p>${r.status==='pending'?'Self-review is unavailable.':escape(r.review_note??'')}</p>`}</article>`).join(''):'<p>No subscription requests have been submitted.</p>')+'<p>Customer request portal: <a href="https://dalasipay-licensing-staging.baboucarrnjie212.workers.dev/subscriptions">Open customer portal</a></p>';
 if(view==='audit')content=rows.length?table(['Action','Business / scope','Actor','Date (UTC)','Details'],rows.map(x=>`<tr><td>${escape(labels(x.event_type))}<small>${escape(x.id)}</small></td><td>${escape(x.business_name??'Platform')}</td><td>${escape(x.actor_user_id)}</td><td>${escape(x.happened_at)}</td><td><details><summary>View audit details</summary><pre>${escape(JSON.stringify(x.details,null,2))}</pre></details></td></tr>`)):'<p>No administrative events recorded.</p>';
 const next=data.rows?.length>100?`<a href="/${view}?offset=${offset+100}">Next page</a>`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${titles[view]} | DalasiPay</title><style>
 *{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#17354c;font:15px system-ui}main{max-width:1360px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;align-items:center;gap:16px;border-bottom:1px solid #d8e2ec;padding-bottom:20px}.brand{font-size:24px;font-weight:800}.badge{background:#e8f5ef;color:#176953;padding:8px 14px;border-radius:30px}nav{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0}nav a{padding:10px 14px;background:white;border:1px solid #d8e2ec;border-radius:9px;text-decoration:none;color:#235879}h1{font-size:34px;letter-spacing:-1px}h2{font-size:21px}p{line-height:1.6}.notice{padding:16px;background:#e7f3f2;border-radius:12px;border:1px solid #c8e0dd}.panel,article{background:white;border:1px solid #dbe5ed;border-radius:14px;padding:24px;margin:18px 0}.plans{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.fact{padding:18px;border:1px solid #e0e8ef;border-radius:10px}small{display:block;color:#617b90;margin-top:6px}.fact strong{display:block;margin-top:10px;overflow-wrap:anywhere}.scroll{overflow:auto}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:16px;border-bottom:1px solid #e5edf3;vertical-align:top}th{font-size:12px;text-transform:uppercase;background:#f8fafc}a{color:#17638c}label{display:flex;flex-direction:column;gap:7px;margin:15px 0}input,textarea,select{padding:11px;border:1px solid #bccfdd;border-radius:8px;font:inherit;max-width:100%;background:white}textarea{min-height:90px}.check{flex-direction:row;align-items:center}.check input{width:18px;height:18px}button{background:#144e73;color:white;border:0;padding:12px 18px;border-radius:8px;font-weight:700;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-width:460px}.success{background:#e5f5eb;padding:15px;border-radius:8px}footer{padding:22px;color:#6f8596}@media(max-width:850px){main{padding:16px}.plans,.facts{grid-template-columns:1fr}h1{font-size:28px}header{flex-wrap:wrap}th,td{padding:12px}}
 </style></head><body><main><header><div class="brand">DalasiPay / Administration</div><span class="badge">Billing and enforcement disabled</span></header>${managementNav}<h1>${titles[view]}</h1><div class="notice">All existing Professional Preview subscriptions retain unlimited access. Administrative approval does not activate a subscription change.</div>${notice?`<p class="success" role="status">${escape(notice)}</p>`:''}<div class="panel">${content}${next}</div><footer>BE Business Solutions · Verified platform administration</footer></main></body></html>`;
}
