import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE).href);
const migration=await readFile(new URL('../supabase/migrations/20261009022714_licensing_management.sql',import.meta.url),'utf8');
const integration=await readFile(new URL('../supabase/migrations/20261009025345_integrated_customer_subscriptions.sql',import.meta.url),'utf8');
const owner='11111111-1111-4111-8111-111111111111',admin='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333',org='44444444-4444-4444-8444-444444444444',org2='55555555-5555-4555-8555-555555555555';
async function fixture(){const db=new PGlite();await db.exec(`CREATE SCHEMA auth;CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;
CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,deleted_at timestamptz,banned_until timestamptz);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE auth.sessions(id uuid PRIMARY KEY,user_id uuid,not_after timestamptz);
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_build_object('session_id',current_setting('request.jwt.claim.sub',true)) $$;
CREATE TABLE organizations(id uuid PRIMARY KEY,name text,currency text,industry text,size_band text,created_by uuid REFERENCES auth.users(id),created_at timestamptz DEFAULT now());
CREATE TABLE organization_members(organization_id uuid REFERENCES organizations(id),user_id uuid REFERENCES auth.users(id),role text);
CREATE TABLE workspace_subscriptions(organization_id uuid PRIMARY KEY REFERENCES organizations(id),plan_id text,status text,professional_preview boolean,source text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE subscription_platform_admins(user_id uuid PRIMARY KEY REFERENCES auth.users(id));CREATE TABLE platform_admin_access_identities(access_subject text PRIMARY KEY,user_id uuid REFERENCES auth.users(id),approved boolean);
CREATE TABLE subscription_change_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),requested_by uuid REFERENCES auth.users(id),requested_plan text NOT NULL CHECK(requested_plan IN ('free','standard','professional')),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 10 AND 1000),status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','cancelled')),created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now(),reviewed_by uuid,reviewed_at timestamptz,review_note text);
CREATE TABLE subscription_admin_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,organization_id uuid REFERENCES organizations(id),request_id uuid REFERENCES subscription_change_requests(id),actor_user_id uuid REFERENCES auth.users(id),event_type text,previous_plan text,proposed_plan text,happened_at timestamptz DEFAULT now(),metadata jsonb DEFAULT '{}');
CREATE FUNCTION prevent_subscription_admin_event_modification() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Events are append-only'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON subscription_admin_events FOR EACH ROW EXECUTE FUNCTION prevent_subscription_admin_event_modification();
CREATE FUNCTION platform_admin_identity_authorized_internal(p_subject text) RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ SELECT EXISTS(SELECT 1 FROM platform_admin_access_identities m JOIN subscription_platform_admins a ON a.user_id=m.user_id WHERE m.access_subject=p_subject AND m.approved) $$;
CREATE FUNCTION review_subscription_request_internal(p_request_id uuid,p_reviewer_id uuid,p_decision text,p_note text) RETURNS boolean LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$ DECLARE r subscription_change_requests%rowtype; BEGIN
 IF p_decision NOT IN ('approved','rejected') OR p_note IS NULL OR length(btrim(p_note))<10 OR length(p_note)>1000 THEN RAISE EXCEPTION 'Invalid review decision'; END IF;
 IF NOT EXISTS(SELECT 1 FROM subscription_platform_admins WHERE user_id=p_reviewer_id) THEN RAISE EXCEPTION 'Platform authorization required'; END IF;
 SELECT * INTO r FROM subscription_change_requests WHERE id=p_request_id FOR UPDATE;
 IF NOT FOUND OR r.status<>'pending' OR r.requested_by=p_reviewer_id THEN RAISE EXCEPTION 'Review unavailable'; END IF;
 UPDATE subscription_change_requests SET status=p_decision,reviewed_by=p_reviewer_id,reviewed_at=now(),review_note=p_note,updated_at=now() WHERE id=r.id;
 INSERT INTO subscription_admin_events(organization_id,request_id,actor_user_id,event_type,proposed_plan) VALUES(r.organization_id,r.id,p_reviewer_id,CASE WHEN p_decision='approved' THEN 'review_approved' ELSE 'review_rejected' END,r.requested_plan);RETURN true;END $$;
REVOKE ALL ON FUNCTION review_subscription_request_internal(uuid,uuid,text,text) FROM PUBLIC,service_role,anon,authenticated;
INSERT INTO auth.users VALUES('${owner}','owner@fixture.test',now(),null,null),('${admin}','admin@fixture.test',now(),null,null),('${other}','other@fixture.test',now(),null,null);
INSERT INTO auth.sessions(id,user_id) VALUES('${owner}','${owner}'),('${other}','${other}'),('${admin}','${admin}');
INSERT INTO organizations(id,name,currency,industry,size_band,created_by) VALUES('${org}','Fixture Trading','GMD','Trading','Small','${owner}'),('${org2}','Another Fixture','GMD','Services','Small','${other}');
INSERT INTO organization_members VALUES('${org}','${owner}','owner'),('${org2}','${other}','owner');
INSERT INTO workspace_subscriptions(organization_id,plan_id,status,professional_preview) VALUES('${org}','professional','professional_preview',true),('${org2}','professional','professional_preview',true);
INSERT INTO subscription_platform_admins VALUES('${admin}');INSERT INTO platform_admin_access_identities VALUES('actual-signed-admin-subject','${admin}',true);`);await db.exec(migration);await db.exec(integration);return db;}
async function customer(db,action,payload={},actor=owner){await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[actor]);await db.exec('SET ROLE authenticated');try{return(await db.query('SELECT customer_subscription_portal($1,$2::jsonb) result',[action,JSON.stringify(payload)])).rows[0].result;}finally{await db.exec('RESET ROLE');}}
async function manage(db,action,payload={},subject='actual-signed-admin-subject'){await db.exec('SET ROLE service_role');try{return(await db.query('SELECT platform_licensing_manage_internal($1,$2,$3::jsonb,0) result',[subject,action,JSON.stringify(payload)])).rows[0].result;}finally{await db.exec('RESET ROLE');}}
const submit={organization_id:org,plan_id:'standard',kind:'upgrade',reason:'Upgrade requested in isolated fixture only'};
test('future workspace is visible in both interfaces with one audited subscription; existing previews untouched',async()=>{const db=await fixture();try{const before=await snapshot(db),newOrg='66666666-6666-4666-8666-666666666666';await db.exec(`INSERT INTO organizations(id,name,created_by) VALUES('${newOrg}','New Fixture Business','${owner}'); INSERT INTO organization_members VALUES('${newOrg}','${owner}','owner');`);const customerRow=(await customer(db,'list')).businesses.find(b=>b.id===newOrg);assert.equal(customerRow.name,'New Fixture Business');assert.ok(customerRow.created_at);assert.equal(customerRow.subscription.plan_id,'free');assert.equal(customerRow.subscription.professional_preview,false);assert.equal((await manage(db,'business',{id:newOrg})).subscription.plan_id,'free');assert.equal((await db.query('SELECT count(*)::int n FROM workspace_subscriptions WHERE organization_id=$1',[newOrg])).rows[0].n,1);assert.deepEqual((await snapshot(db)).filter(s=>s.organization_id!==newOrg),before);assert.equal((await manage(db,'audit')).rows[0].details.proposed_plan,'free');assert.equal((await db.query('SELECT metadata FROM subscription_admin_events WHERE organization_id=$1',[newOrg])).rows[0].metadata.initial_assignment,true);await assert.rejects(db.exec(`INSERT INTO organizations(id,name) VALUES('${newOrg}','Duplicate')`));}finally{await db.close();}});
test('workspace creation rolls back if initial subscription audit cannot be recorded',async()=>{const db=await fixture();try{await db.exec("CREATE FUNCTION deny_initial_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Audit unavailable'; END $$; CREATE TRIGGER test_initial_audit BEFORE INSERT ON subscription_admin_events FOR EACH ROW EXECUTE FUNCTION deny_initial_audit();");const id='77777777-7777-4777-8777-777777777777';await assert.rejects(db.exec(`INSERT INTO organizations(id,name,created_by) VALUES('${id}','Failed Fixture','${owner}')`));assert.equal((await db.query('SELECT count(*)::int n FROM organizations WHERE id=$1',[id])).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM workspace_subscriptions WHERE organization_id=$1',[id])).rows[0].n,0);}finally{await db.close();}});
test('customer catalogue follows administrator drafts without changing active preview entitlements',async()=>{const db=await fixture();try{const before=await snapshot(db);const draft=(await manage(db,'plans')).rows.find(p=>p.plan_id==='free');await manage(db,'save_plan',{...draft,label:'Configured Free',limits:{...draft.limits,employees:8},features:['coreAccounting','budgets']});const plan=(await customer(db,'list')).plans.find(p=>p.plan_id==='free');assert.equal(plan.label,'Configured Free');assert.equal(plan.limits.employees,8);assert.deepEqual(plan.features,['coreAccounting','budgets']);assert.deepEqual(await snapshot(db),before);}finally{await db.close();}});
async function snapshot(db){return(await db.query('SELECT * FROM workspace_subscriptions ORDER BY organization_id')).rows;}
test('management profiles/catalogue and tenant-scoped portal return only trusted real data; anonymous/admin spoof denied',async()=>{const db=await fixture();try{const profile=await manage(db,'business',{id:org});assert.equal(profile.profile.name,'Fixture Trading');assert.equal(profile.account.email,'owner@fixture.test');assert.equal(profile.details,null);const data=await customer(db,'list');assert.equal(data.businesses.length,1);assert.equal(data.businesses[0].id,org);assert.equal((await manage(db,'plans')).enforcement,false);await assert.rejects(manage(db,'plans',{},'unappointed-subject'));await db.exec('SET ROLE anon');await assert.rejects(db.query("SELECT customer_subscription_portal('list')"));await db.exec('RESET ROLE');await db.exec('SET ROLE authenticated');await assert.rejects(db.query("SELECT platform_licensing_manage_internal('actual-signed-admin-subject','plans')"));await assert.rejects(db.query('SELECT * FROM licensing_plan_drafts'));await db.exec('RESET ROLE');}finally{await db.close();}});
test('customer submission and administrator review audited atomically; subscription preview unchanged and repeat denied',async()=>{const db=await fixture();try{const before=await snapshot(db);const r=await customer(db,'submit',submit);await assert.rejects(customer(db,'submit',submit));await assert.rejects(customer(db,'submit',{...submit,organization_id:org2}));assert.equal((await manage(db,'requests')).rows.length,1);await manage(db,'review',{id:r.request_id,decision:'approved',note:'Reviewed in isolated fixture only'});assert.equal((await customer(db,'list')).businesses[0].requests[0].status,'approved');assert.equal((await manage(db,'audit')).rows.length,2);await assert.rejects(manage(db,'review',{id:r.request_id,decision:'rejected',note:'Cannot review again'}));assert.deepEqual(await snapshot(db),before);}finally{await db.close();}});
test('request cancellation requires requester ownership; revoked membership, unconfirmed account and self-review denied',async()=>{const db=await fixture();try{const r=await customer(db,'submit',submit);await assert.rejects(customer(db,'cancel',{id:r.request_id},other));await db.exec(`INSERT INTO subscription_platform_admins VALUES('${owner}');INSERT INTO platform_admin_access_identities VALUES('owner-admin-subject','${owner}',true)`);await assert.rejects(manage(db,'review',{id:r.request_id,decision:'approved',note:'Self review must fail'},'owner-admin-subject'));await customer(db,'cancel',{id:r.request_id});await assert.rejects(customer(db,'cancel',{id:r.request_id}));await db.exec(`UPDATE auth.users SET email_confirmed_at=null WHERE id='${owner}'`);await assert.rejects(customer(db,'list'));await db.exec(`UPDATE auth.users SET email_confirmed_at=now() WHERE id='${owner}'; DELETE FROM auth.sessions WHERE user_id='${owner}'`);await assert.rejects(customer(db,'list'));}finally{await db.close();}});
test('draft configuration and renewal notes use optimistic versions and immutable audit, never enforce entitlements',async()=>{const db=await fixture();try{const before=await snapshot(db);const draft=(await manage(db,'plans')).rows.find(x=>x.plan_id==='free');const payload={...draft,label:'Draft Free',limits:{...draft.limits,employees:7},features:['coreAccounting']};await manage(db,'save_plan',payload);await assert.rejects(manage(db,'save_plan',payload));await assert.rejects(manage(db,'save_plan',{...payload,version:2,limits:{employees:-1}}));await manage(db,'save_details',{id:org,version:0,renewal_date:'2027-01-01',notes:'Planning only'});await assert.rejects(manage(db,'save_details',{id:org,version:0,notes:'Stale'}));assert.equal((await manage(db,'business',{id:org})).details.notes,'Planning only');await assert.rejects(db.exec('DELETE FROM licensing_management_events'));await assert.rejects(db.exec('TRUNCATE licensing_management_events'));assert.deepEqual(await snapshot(db),before);}finally{await db.close();}});
test('audit failure rolls back customer request, draft and review writes',async()=>{const db=await fixture();try{await db.exec("CREATE FUNCTION fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit unavailable'; END $$; CREATE TRIGGER test_audit_fail BEFORE INSERT ON subscription_admin_events FOR EACH ROW EXECUTE FUNCTION fail_audit();");await assert.rejects(customer(db,'submit',submit));assert.equal((await db.query('SELECT count(*)::int n FROM subscription_change_requests')).rows[0].n,0);await db.exec('DROP TRIGGER test_audit_fail ON subscription_admin_events');const r=await customer(db,'submit',submit);await db.exec('CREATE TRIGGER test_audit_fail BEFORE INSERT ON subscription_admin_events FOR EACH ROW EXECUTE FUNCTION fail_audit()');await assert.rejects(manage(db,'review',{id:r.request_id,decision:'approved',note:'Audit must rollback this'}));assert.equal((await customer(db,'list')).businesses[0].requests[0].status,'pending');await db.exec('CREATE TRIGGER test_draft_audit_fail BEFORE INSERT ON licensing_management_events FOR EACH ROW EXECUTE FUNCTION fail_audit()');const draft=(await manage(db,'plans')).rows[0];await assert.rejects(manage(db,'save_plan',{...draft,label:'Failed edit'}));assert.equal((await manage(db,'plans')).rows[0].version,1);}finally{await db.close();}});
